### ISSUE TITLE
Darle entidad a la coordenada

### ISSUE THREAD

**Issue by diegosanchez** [fpaus/Algo3-TP2#33]
Debería existir una entiadad `Punto`.

```java
    public Casillero getCasilleroEnPosicion(int x, int y) throws CasilleroFueraDelLosLimitesDelTableroExcepcion {
        try {
            return casilleros[x][y];
        } catch (ArrayIndexOutOfBoundsException ex) {
            throw new CasilleroFueraDelLosLimitesDelTableroExcepcion();
        }
    }
```

Será necesario cuando necesiten calcular distancias, casilleros a la izquierda, derecha, etc.

**Comment by franyanes** [comment]
Hola Diego.

Estamos pensando en crear la clase Coordenadas, que va a contener dos atributos, "x" e "y". En el caso de que necesitemos acceder a la matriz, tendríamos que depender de getters, o sino podríamos pasarle la matriz a la instancia de Coordenadas para evitar getters.

` return casilleros[coordenadas.getX()][coordenadas.getY()];`

Qué opinás?
